server:
  port: 8090
  servlet:
    encoding:
      charset: utf-8
      force: true
spring:
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/testdb?characterEncoding=utf8
    #url: jdbc:mysql://127.0.0.1:3306/shopdb?serverTimezone=Asia/Seoul
    username: smuser
    password: 111111
mybatis:
  type-aliases-package: edu.sm.sm2025team4.dto
  mapper-locations: classpath:/mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: false
logging:
  level:
    root: info
app:
  dir:
    imgsdir: file:///C:/java/sm2025team4/imgs     # 화면 출력 용
    uploadimgsdir: C:/java/sm2025team4/imgs   # 파일 Write 용